export interface ExecutionResult {

    /**
     * Indicates whether execution completed successfully.
     */
    success: boolean;

    /**
     * Response generated by the model.
     */
    response: string;

    /**
     * Prompt tokens.
     */
    promptTokens?: number;

    /**
     * Completion tokens.
     */
    completionTokens?: number;

    /**
     * Total tokens.
     */
    totalTokens?: number;

    /**
     * Execution duration (ms).
     */
    duration?: number;

    /**
     * Provider used.
     */
    provider?: string;

    /**
     * Model used.
     */
    model?: string;

    /**
     * Optional execution metadata.
     */
    metadata?: Record<string, unknown>;

}