/**
 * Standard execution result returned by every runtime agent.
 */
export interface AgentResult {
    /**
     * Indicates whether execution completed successfully.
     */
    success: boolean;

    /**
     * Final output generated by the agent.
     */
    output: string;

    /**
     * Optional structured payload.
     */
    data?: unknown;

    /**
     * Execution error, if any.
     */
    error?: Error | string;

    /**
     * Execution time in milliseconds.
     */
    executionTime?: number;

    /**
     * Optional token usage statistics.
     */
    usage?: {
        promptTokens?: number;
        completionTokens?: number;
        totalTokens?: number;
    };

    /**
     * Model used during execution.
     */
    model?: string;

    /**
     * Provider used during execution.
     */
    provider?: string;

    /**
     * Additional runtime metadata.
     */
    metadata?: Record<string, unknown>;
}