import { randomUUID } from "crypto";

import { type VaultContext } from "@aios/shared";

import {
  isEncryptionConfigured,
  createSpaceManifest,
  listSpaceManifests,
  getActiveEncryptionKeyAsync,
  resolveHmacSecret,
  generateEncryptionKey,
  normalizeTBitSpaceId,
  getTBitSpacePaths,
  setActiveTBitSpacesRoot,
  normalizeTBitVaultRoot,
} from "@muf/tbit-core";
import { TBitStorageService, TBitStorageConfig } from "@muf/tbit-core";

import {
  Kernel,
  MemoryVaultProvider,
  WorkflowVaultProvider,
  AgentVaultProvider,
  QVaultVaultProvider,
  LlmVaultProvider,
  VAULT_PROVIDER_IDS,
} from "@aios/kernel";

import path from "path";

/**
 * Request payload for initializing a vault.
 */
export interface VaultInitRequest {
  /** Absolute or relative path to the user-selected vault root. */
  vaultRoot: string;
  /** Unique identifier for the user owning the default space. */
  userId: string;
  /** Optional human-readable label for the primary space. */
  label?: string;
  /** When true, forces generation of a new encryption key if none is configured. */
  generateKey?: boolean;
}

/**
 * Response returned after a successful vault initialization.
 */
export interface VaultInitResponse {
  /** Identifier of the default T-Bit container/space. */
  containerId: string;
  /** Identifier of the default T-Bit space (same as containerId). */
  spaceId: string;
  /** Human-readable label of the primary space. */
  label: string;
  /** Normalized vault root path. */
  vaultRoot: string;
  /** Identifier of the active vault — generated by the bootstrap service. */
  vaultId: string;
  /** Active encryption key identifier used for T-Bit integrity. */
  encryptionKeyId: string;
  /** Whether the Kernel reports all subsystems ready. */
  kernelReady: boolean;
  /** Stage 8.2 vault readiness: true once T-Bit storage recovery succeeded. */
  vaultReady: boolean;
  /** Per-subsystem readiness map. */
  subsystems: Record<string, boolean>;
  /** ISO-8601 timestamp of initialization completion. */
  initializedAt: string;
}

/**
 * Response describing the current vault bootstrap status.
 */
export interface VaultStatusResponse {
  /** Whether the vault has been initialized in this process. */
  initialized: boolean;
  /** Normalized vault root path, if initialized. */
  vaultRoot?: string;
  /** Identifier of the active vault, if initialized. */
  vaultId?: string;
  /** Number of T-Bit spaces discovered. */
  spacesCount: number;
  /** Whether at least one encryption key is configured. */
  encryptionConfigured: boolean;
  /** Whether the Kernel reports all subsystems ready. */
  kernelReady: boolean;
  /** Stage 8.2 vault readiness: true once T-Bit storage recovery succeeded. */
  vaultReady: boolean;
  /** Per-subsystem readiness map. */
  subsystems: Record<string, boolean>;
  /** ISO-8601 timestamp of the last status verification. */
  lastVerifiedAt?: string;
  /** Error message, if the vault is not initialized. */
  error?: string;
}

/**
 * Names of the subsystems verified during bootstrap.
 *
 * Stage 8.4 maps each subsystem to a vault-aware provider:
 *  - memory   → `MemoryVaultProvider`
 *  - workflow → `WorkflowVaultProvider`
 *  - provider → aggregate readiness of all vault providers
 *  - agent    → `AgentVaultProvider`
 *  - qvault   → `QVaultVaultProvider`
 *  - llm      → `LlmVaultProvider`
 *
 * The "provider" subsystem is reported as ready when every
 * registered vault provider reports ready via
 * `Kernel.initializeProviders()`.
 */
const SUBSYSTEM_NAMES = ["memory", "workflow", "provider", "agent", "qvault", "llm"] as const;

/**
 * Stage 8.4 — Vault Bootstrap Service
 *
 * Orchestrates the linear initialization of the T-Bit stack
 * (Vault → Encryption → Manifest → Storage → Kernel → Providers)
 * against a user-selected vault root.
 *
 * **Deterministic bootstrap order (per `AIOS_ENGINEERING_AUDIT_v2.md` §5):**
 *  1. `setActiveTBitSpacesRoot(vaultRoot + "/spaces")` — vault-aware
 *     paths via `@muf/tbit-core/tbitRuntimePaths`.
 *  2. Ensure an encryption key exists (generate if none configured).
 *  3. Create the primary space manifest.
 *  4. Recover T-Bit storage to validate the container is usable.
 *  5. Construct a `VaultContext` (Stage 8.4 wiring point).
 *  6. Construct a `Kernel` and register every vault-aware provider.
 *  7. Call `kernel.initializeProviders()` to fan-out the vault
 *     context to every provider.
 *  8. Verify subsystem readiness from the provider fan-out result.
 *  9. Emit `vault.opened` (handled internally by `Kernel`).
 *
 * **Architecture compliance:**
 *  - "Vault Lifecycle" (§16): single active vault, linear bootstrap.
 *  - "Provider Architecture" (§16): providers initialized with
 *    `VaultContext`, no hardcoded paths.
 *  - "Kernel Responsibilities" (§16): Kernel orchestrates; storage
 *    stays in `@muf/tbit-core`.
 *  - "Every Subsystem Initializes Through Bootstrap" (§3):
 *    `VaultBootstrapService` is the single initialization entry point.
 */
export class VaultBootstrapService {
  private vaultRoot: string | null = null;
  private spacesRoot: string | null = null;
  private vaultId: string | null = null;
  private initialized = false;
  private kernelReady = false;
  private subsystems: Record<string, boolean> = {};
  /** Stage 8.4 — Live Kernel instance kept in scope for inspection. */
  private kernel: Kernel | null = null;

  /**
   * Initialize a vault at the user-selected root path.
   *
   * The bootstrap sequence is linear and strictly ordered:
   * 1. Normalize and set the vault root as the active T-Bit spaces root.
   * 2. Ensure an encryption key exists (generate if none configured).
   * 3. Create the primary space manifest inside the vault.
   * 4. Recover T-Bit storage to validate the container is usable.
   * 5. Construct a `VaultContext` and attach it to the Kernel.
   * 6. Register vault-aware providers with the Kernel.
   * 7. Fan-out initialization via `kernel.initializeProviders()`.
   * 8. Aggregate per-provider readiness into subsystem readiness.
   *
   * @param req - Initialization request containing vaultRoot and userId.
   * @returns Initialization result with subsystem readiness.
   * @throws {Error} if vaultRoot or userId is empty.
   */
  async initialize(req: VaultInitRequest): Promise<VaultInitResponse> {
    const { vaultRoot, userId, label, generateKey } = req;

    if (!vaultRoot?.trim()) {
      throw new Error("vaultRoot is required.");
    }
    if (!userId?.trim()) {
      throw new Error("userId is required.");
    }

    // 1) Normalize and set the vault root as the active spaces root
    const normalizedVaultRoot = normalizeTBitVaultRoot(vaultRoot.trim());
    const spacesRoot = path.join(normalizedVaultRoot, "spaces");
    setActiveTBitSpacesRoot(spacesRoot);

    this.vaultRoot = normalizedVaultRoot;
    this.spacesRoot = spacesRoot;
    this.vaultId = Kernel.generateVaultId();

    const spaceId = `user:${normalizeTBitSpaceId(userId.trim())}`;
    const spaceLabel = label?.trim() ?? `AIOS Space ${userId.trim()}`;

    // 2) Encryption key — generate if requested and none is configured yet
    let encryptionKeyId: string;
    const configured = await isEncryptionConfigured();

    if (generateKey && !configured) {
      const key = await generateEncryptionKey(`key-${normalizeTBitSpaceId(userId.trim())}`);
      encryptionKeyId = key.id;
    } else {
      const key = configured
        ? await getActiveEncryptionKeyAsync()
        : await generateEncryptionKey(`key-${normalizeTBitSpaceId(userId.trim())}`);
      encryptionKeyId = key.id;
    }

    // 3) Persist the space manifest + directory scaffold at vaultRoot/spaces/<spaceId>
    const manifest = await createSpaceManifest({ spaceId, label: spaceLabel, userId: userId.trim() });

    // 4) Recover T-Bit storage to validate the container is usable with the active key
    const paths = getTBitSpacePaths(spaceId);
    const [hmacKeyId, hmacSecret] = await resolveHmacSecret();

    const config: TBitStorageConfig = {
      name: "default",
      containerPath: paths.containerPath,
      metadataPath: paths.metadataPath,
      walPath: paths.walPath,
      snapshotsDir: paths.snapshotsDir,
      replicasDir: paths.replicasDir,
      exportsDir: path.join(paths.rootDir, "exports"),
      lockPath: paths.lockPath,
      hmacSecrets: new Map([[hmacKeyId, hmacSecret]]),
      hmacKeyId,
      maxDatoBytes: 64 * 1024,
      maxRecords: 500,
      containerSizeMB: 10,
    };

    const storage = new TBitStorageService(config);
    await storage.recover();

    // 5) Construct the VaultContext
    const newVaultId = this.vaultId;
    const vaultContext: VaultContext = {
      vaultId: newVaultId,
      vaultRoot: normalizedVaultRoot,
      spacesRoot,
      spaceId: manifest.spaceId,
      encryptionKeyId,
      userId: userId.trim(),
      label: spaceLabel,
      initializedAt: new Date().toISOString(),
    };

    // 6) Construct the Kernel, attach the VaultContext, register providers
    this.kernel = new Kernel(vaultContext);
    this.registerVaultProviders(this.kernel);
    this.kernel.setVaultContext(vaultContext);

    // 7) Fan-out initialization
    await this.kernel.initializeProviders();

    // 8) Verify subsystem readiness from the provider fan-out
    this.subsystems = this.verifySubsystems();
    this.kernelReady = Object.values(this.subsystems).every((v) => v === true);
    this.initialized = true;

    return {
      containerId: manifest.spaceId,
      spaceId: manifest.spaceId,
      label: manifest.label,
      vaultRoot: normalizedVaultRoot,
      vaultId: newVaultId,
      encryptionKeyId,
      kernelReady: this.kernelReady,
      vaultReady: true,
      subsystems: this.subsystems,
      initializedAt: new Date().toISOString(),
    };
  }

  /**
   * Get the current vault bootstrap status.
   *
   * Reports whether the vault has been initialized in this process, the
   * number of discovered spaces, encryption readiness, vault id, and
   * per-subsystem readiness.
   *
   * @returns Vault status response.
   */
  async getStatus(): Promise<VaultStatusResponse> {
    if (!this.initialized || !this.vaultRoot) {
      return {
        initialized: false,
        spacesCount: 0,
        encryptionConfigured: false,
        kernelReady: false,
        vaultReady: false,
        subsystems: {},
        error: "Vault not initialized",
      };
    }

    const encryptionConfigured = await isEncryptionConfigured();
    const spaces = await listSpaceManifests();

    return {
      initialized: true,
      vaultRoot: this.vaultRoot,
      vaultId: this.vaultId ?? undefined,
      spacesCount: spaces.length,
      encryptionConfigured,
      kernelReady: this.kernelReady,
      vaultReady: true,
      subsystems: this.subsystems,
      lastVerifiedAt: new Date().toISOString(),
    };
  }

  /**
   * Stage 8.4 — Dispose the active vault.
   *
   * Emits the `vault.closed` event on the Kernel event bus and clears
   * the service's internal references. The Kernel is intentionally NOT
   * destroyed because providers may still need to surface readiness
   * information through the service.
   */
  async dispose(): Promise<void> {
    if (this.kernel) {
      await this.kernel.disposeVault();
    }
    this.kernel = null;
    this.kernelReady = false;
    this.subsystems = {};
    this.initialized = false;
    this.vaultRoot = null;
    this.spacesRoot = null;
    this.vaultId = null;
  }

  /**
   * Read-only accessor for the live Kernel instance.
   *
   * Exposed for integration tests and debugging — production code MUST
   * NOT depend on this getter for runtime operations.
   */
  getKernelForTesting(): Kernel | null {
    return this.kernel;
  }

  /**
   * Register a listener for the `vault.opened` event emitted by the
   * Kernel event bus.
   *
   * If a Kernel is already active, the listener is attached immediately
   * to its event bus. If the Kernel is not yet created, the listener is
   * queued and the service's `initialize()` method is wrapped so that
   * the listener is attached to the Kernel's event bus as soon as the
   * Kernel is constructed, but BEFORE `initializeProviders()` is called
   * (which is where `vault.opened` is emitted).
   *
   * This helper exists to enable deterministic event tests without
   * monkey-patching internal service methods. It is intentionally
   * separate from `getKernelForTesting()` to avoid leaking the Kernel
   * surface in production callers.
   *
   * Returns an unsubscribe function that restores the original
   * `initialize()` method (if it was wrapped) and is otherwise a no-op.
   */
  onVaultOpenedForTesting(listener: (payload: unknown) => void): () => void {
    if (this.kernel) {
      const k = this.kernel as unknown as {
        events: { on: (n: string, cb: (p: unknown) => void) => void };
      };
      k.events.on("vault.opened", listener);
      return () => {
        /* no-op unsubscribe; EventEmitter does not expose .off publicly */
      };
    }
    // Queue the listener — wrap initialize() to attach the listener
    // immediately after the Kernel is constructed and BEFORE
    // initializeProviders() emits vault.opened.
    const self = this;
    const originalInit = self.initialize.bind(self);
    const wrappedInit = async (req: VaultInitRequest): Promise<VaultInitResponse> => {
      // Reach into the service to attach the listener at the right
      // moment. We can't observe `this.kernel = new Kernel(...)`
      // synchronously from outside without monkey-patching the
      // constructor, but we CAN observe `initializeProviders()` by
      // wrapping it on the instance after construction.
      //
      // Strategy: temporarily override `initializeProviders` on the
      // Kernel prototype to call our listener before the real
      // implementation. This is invasive but only triggered when
      // onVaultOpenedForTesting is called, which is test-only.
      const originalKernelInitProviders = Kernel.prototype.initializeProviders;
      Kernel.prototype.initializeProviders = async function patched(this: unknown, ...args: unknown[]) {
        // Attach our listener on the Kernel event bus BEFORE the real
        // initializeProviders emits vault.opened.
        const k = this as unknown as {
          events: { on: (n: string, cb: (p: unknown) => void) => void };
        };
        k.events.on("vault.opened", listener);
        return (originalKernelInitProviders as (...a: unknown[]) => unknown).apply(this, args) as Promise<void>;
      };
      try {
        return await originalInit(req);
      } finally {
        Kernel.prototype.initializeProviders = originalKernelInitProviders;
      }
    };
    (this as unknown as { initialize: (req: VaultInitRequest) => Promise<VaultInitResponse> }).initialize = wrappedInit;
    return () => {
      (this as unknown as { initialize: (req: VaultInitRequest) => Promise<VaultInitResponse> }).initialize = originalInit;
    };
  }

  /**
   * Register every vault-aware provider with the Kernel.
   *
   * Order is meaningful for readiness reporting: providers are
   * registered in the same order as `VAULT_PROVIDER_IDS`. The
   * mapping between provider id and subsystem name is enforced by
   * `verifySubsystems()`.
   */
  private registerVaultProviders(kernel: Kernel): void {
    const providers = [
      new MemoryVaultProvider(),
      new WorkflowVaultProvider(),
      new AgentVaultProvider(),
      new QVaultVaultProvider(),
      new LlmVaultProvider(),
    ];

    for (const provider of providers) {
      kernel.providers.register(provider);
    }
  }

  /**
   * Verify subsystem readiness.
   *
   * Stage 8.4 derives subsystem readiness from the per-provider
   * fan-out result. Each subsystem maps to one vault provider:
   *
   * | subsystem  | provider id        |
   * |------------|--------------------|
   * | memory     | memory-vault       |
   * | workflow   | workflow-vault     |
   * | provider   | aggregate (true if all providers ready) |
   * | agent      | agent-vault        |
   * | qvault     | qvault-vault       |
   * | llm        | llm-vault          |
   *
   * @returns A map of subsystem name to readiness boolean.
   */
  private verifySubsystems(): Record<string, boolean> {
    const providers = this.kernel?.getProviderReadiness() ?? {};
    const result: Record<string, boolean> = {};

    for (const name of SUBSYSTEM_NAMES) {
      result[name] = false;
    }

    result.memory = providers["memory-vault"] === true;
    result.workflow = providers["workflow-vault"] === true;
    result.agent = providers["agent-vault"] === true;
    result.qvault = providers["qvault-vault"] === true;
    result.llm = providers["llm-vault"] === true;
    // "provider" is the aggregate readiness of all vault providers.
    const providerIds = Object.keys(providers);
    if (providerIds.length === 0) {
      result.provider = false;
    } else {
      result.provider = providerIds.every((id) => providers[id] === true);
    }

    return result;
  }
}

/** Singleton instance of the vault bootstrap service. */
export const vaultBootstrapService = new VaultBootstrapService();

/** Re-export VAULT_PROVIDER_IDS for consumers that need the canonical provider list. */
export { VAULT_PROVIDER_IDS };
export { randomUUID as _vaultRandomUUID };
