/**
 * MUF Labs
 * @package agents
 *
 * Common request/response types shared by the Agents package.
 */

export interface AgentRequest {
    /**
     * Command or operation requested.
     */
    command: string;

    /**
     * Prompt or input provided to the agent.
     */
    prompt: string;
}

export interface AgentResponse {
    /**
     * Indicates whether the operation completed successfully.
     */
    success: boolean;

    /**
     * Output generated by the agent.
     */
    output: string;
}