/**
 * Stage 8.4 — Vault Context
 *
 * The `VaultContext` is the canonical, dependency-injected representation
 * of the active vault that every subsystem receives at initialization time.
 *
 * It is the **only** mechanism by which subsystems learn about their
 * runtime environment. Subsystems MUST NOT read environment variables,
 * hardcoded paths, or any global state to resolve paths.
 *
 * **Architecture (per `AIOS_ENGINEERING_AUDIT_v2.md` §3):**
 * - "No Hardcoded Filesystem Paths" — all paths resolve through `tbitRuntimePaths`
 *   keyed off the active `VaultContext.spacesRoot`.
 * - "Composition Over Coupling" — `VaultContext` is injected via the
 *   `ProviderManager.initialize({ vaultContext })` contract, not via global state.
 * - "The Vault Is the Root of Persistent State" — every persistent asset
 *   derives from the user-selected vault folder.
 *
 * **Stage 8.4 wiring point:** `VaultBootstrapService.initializeKernel()`
 * constructs a `VaultContext` after `setActiveTBitSpacesRoot()` is called
 * and passes it to `Kernel.initializeProviders()`. Each provider then
 * resolves its runtime paths relative to `vaultContext.spacesRoot`.
 *
 * @see `VaultBootstrapService` — constructor of the context
 * @see `Kernel.initializeProviders()` — fan-out initializer
 * @see `IProvider.initialize()` — per-provider contract
 */
export interface VaultContext {
  /**
   * Unique identifier of the active vault.
   *
   * Stage 8.2/8.4 MVP enforces a single vault per session; this id
   * is generated by `VaultBootstrapService` at initialize time.
   */
  readonly vaultId: string;

  /**
   * Absolute, normalized path to the user-selected vault root.
   *
   * This is the directory the user picked via the File System Access API
   * (web) or the equivalent native picker (desktop). The Kernel and all
   * providers treat this as the **single source of truth** for filesystem
   * layout.
   */
  readonly vaultRoot: string;

  /**
   * Absolute, normalized path to the vault's T-Bit spaces directory.
   *
   * Conventionally `vaultRoot + "/spaces"`. This is the value passed to
   * `setActiveTBitSpacesRoot()` during bootstrap, so that
   * `tbitRuntimePaths.getTBitSpacePaths()` automatically returns
   * vault-scoped paths.
   */
  readonly spacesRoot: string;

  /**
   * Identifier of the primary T-Bit space (same as container id).
   *
   * Used by the Kernel and providers to scope operations to the
   * user's default space.
   */
  readonly spaceId: string;

  /**
   * Identifier of the active encryption key.
   *
   * Provided by `VaultBootstrapService` after `getEncryptionKeyStatus()`
   * or `generateEncryptionKey()`.
   */
  readonly encryptionKeyId: string;

  /**
   * Identifier of the active user (owner of the default space).
   *
   * Mirrors `VaultInitRequest.userId`.
   */
  readonly userId: string;

  /**
   * Human-readable label of the vault/space.
   */
  readonly label: string;

  /**
   * ISO-8601 timestamp of vault initialization.
   */
  readonly initializedAt: string;
}

/**
 * Vault-aware initialization contract for Kernel providers.
 *
 * Every provider that needs to resolve paths relative to the active
 * vault MUST implement `initializeProvider(config)` where
 * `config.vaultContext` carries the `VaultContext`.
 *
 * The Kernel calls this on every registered provider via
 * `ProviderManager.initializeAll({ vaultContext })`. Providers must
 * be idempotent — calling `initializeProvider` twice with the same
 * context is a no-op.
 *
 * **Path resolution rule:** Providers MUST derive every filesystem
 * path from `config.vaultContext.spacesRoot` (via `getTBitSpacePaths(spaceId)`)
 * and MUST NOT use `process.cwd()` or any other hardcoded location.
 */
export interface VaultProviderConfig {
  /**
   * Active vault context — the only dependency a provider needs to
   * resolve its runtime paths.
   */
  readonly vaultContext: VaultContext;
}

/**
 * Capability a provider can declare in its `info.capabilities` field
 * to advertise that it is vault-aware. `Kernel.initializeProviders()`
 * uses this for readiness verification.
 *
 * - `'vault.read'`  — provider reads vault-scoped paths
 * - `'vault.write'` — provider writes to vault-scoped paths
 */
export type VaultCapability = 'vault.read' | 'vault.write';

/**
 * Vault lifecycle event names. Emitted by `VaultBootstrapService`
 * on the Kernel's event bus (or a dedicated vault event bus).
 *
 * Subsystems subscribe via `kernel.events.on('vault.opened', ...)`
 * to refresh their internal state when the vault changes.
 */
export const VAULT_EVENTS = {
  /** Emitted once after `VaultBootstrapService.initialize()` succeeds. */
  OPENED: 'vault.opened',
  /** Emitted on `VaultBootstrapService.dispose()` or process shutdown. */
  CLOSED: 'vault.closed',
  /**
   * Emitted when a new vault replaces the active one.
   *
   * Stage 8.4 MVP supports only one active vault per session; this
   * event is emitted on re-initialization for forward compatibility.
   */
  SWITCHED: 'vault.switched',
} as const;

/**
 * Payload type for the `vault.opened` event.
 */
export interface VaultOpenedPayload {
  readonly vaultContext: VaultContext;
  /** Per-subsystem readiness map mirroring `VaultInitResponse.subsystems`. */
  readonly subsystems: Record<string, boolean>;
}

/**
 * Payload type for the `vault.closed` event.
 */
export interface VaultClosedPayload {
  readonly vaultId: string;
  readonly closedAt: string;
}

/**
 * Payload type for the `vault.switched` event.
 */
export interface VaultSwitchedPayload {
  /** Vault context for the previous (closed) vault, if any. */
  readonly previous: VaultContext | null;
  /** Vault context for the newly opened vault. */
  readonly current: VaultContext;
}
